### ISSUE TITLE
为什么点击下载没反应，纯小白

### ISSUE THREAD

**Issue by LeoZhu6** [lindaoling/jable-download#2]

**Comment by lindaoling** [comment]
有两步重要流程，你是否已经按说明执行了
> 1 右击 init.bat,以管理员身份运行，会向注册表添加一个协议注册
> 2 chrome浏览器中，点击扩展图标 -> 选项，填写默认下载目录，点保存

如果已经执行了以上两步，点击下载前，按F12打开浏览器开发都工具，再点下载，看下是否有报错信息

**Comment by bnlife** [comment]
我也遇见相同的问题。之前使用正常，但是我重新安装chrome之后，点击下载按钮便没有反应了。

**Comment by bnlife** [comment]
找到原因了，m3u8注册路径中不能有空格

**Comment by HChengNuoH** [comment]
> 找到原因了，m3u8注册路径中不能有空格

感谢感谢。我也是这个问题。EDGE浏览器也能用。我还特地下载了一个谷歌浏览器当时也不能下载差点吓死我。
